services:
  - type: web
    name: greencard-insights-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DATABASE_URL

        fromDatabase:
          name: greencard-db
          property: connectionString

databases:
  - name: greencard-db
    databaseName: immigratrack
    user: immigratrack_user
